name: mirror.yml

on:
   schedule:
       - cron: "0 0 * * *"
   workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # YAC - Yet Another Coupler
          - mirror_name: yac-mirror
            upstream: https://gitlab.dkrz.de/dkrz-sw/yac
          # YAXT - YetAnother eXchange Tool
          - mirror_name: yaxt-mirror
            upstream: https://gitlab.dkrz.de/dkrz-sw/yaxt
    concurrency:
      group: ${{ matrix.upstream }}
      cancel-in-progress: true
    steps:
      - run: git clone --bare "${{ matrix.upstream }}" .
      - run: git push --mirror "https://x:$GITHUB_TOKEN@github.com/pism/${{ matrix.mirror_name }}.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
